name: calendar_reminder_app
description: A comprehensive calendar and reminder application with notes and alarms.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  # flutter_local_notifications: ^16.3.2  # Temporarily disabled for Android build
  # timezone: ^0.9.2  # Temporarily disabled for Android build
  
  # Calendar UI
  table_calendar: ^3.0.9
  
  # State management
  provider: ^6.1.1
  
  # UI components
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  
  # Audio for alarms
  # audioplayers: ^5.2.1  # Temporarily disabled for Android build
  
  # Permissions
  permission_handler: ^11.1.0
  
  # File system
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/ 